export const styles = {
  container: {
    minHeight: '100vh',
    minHeight: '100dvh',
    backgroundColor: '#F4ECD8',
    padding: '30px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    maxWidth: '500px',
    margin: '0 auto',
    boxSizing: 'border-box',
    fontFamily: 'serif',
  },
  title: {
    color: '#4A3B32',
    textAlign: 'center',
    marginBottom: '40px',
    fontSize: '18px',
    borderBottom: '2px solid #C1A68D',
    paddingBottom: '10px',
  },
  button: {
    backgroundColor: '#4A3B32',
    color: '#F4ECD8',
    padding: '15px',
    borderRadius: '5px',
    border: 'none',
    fontSize: '16px',
    fontFamily: 'serif',
    fontWeight: 'bold',
    cursor: 'pointer',
    width: '100%',
    marginBottom: '15px',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
  },
  primaryButton: {
    backgroundColor: '#4A3B32'
  },
  cancelBtn: {
    backgroundColor: 'transparent',
    color: '#8C271E',
    padding: '15px',
    border: 'none',
    fontSize: '16px',
    fontFamily: 'serif',
    cursor: 'pointer',
    width: '100%',
  },
  input: {
    backgroundColor: '#E8DCC4',
    border: '1px solid #C1A68D',
    padding: '15px',
    borderRadius: '5px',
    fontFamily: 'serif',
    fontSize: '16px',
    color: '#4A3B32',
    marginBottom: '25px',
    width: '100%',
    boxSizing: 'border-box',
  },
  textArea: {
    backgroundColor: '#E8DCC4',
    border: '1px solid #C1A68D',
    padding: '15px',
    borderRadius: '5px',
    fontFamily: 'serif',
    fontSize: '18px',
    color: '#4A3B32',
    height: '250px',
    resize: 'none',
    marginBottom: '15px',
    width: '100%',
    boxSizing: 'border-box',
  },
  label: {
    color: '#4A3B32',
    fontSize: '16px',
    marginBottom: '5px',
    fontWeight: 'bold',
    display: 'block',
  },
  letterPaper: {
    backgroundColor: '#FAF5EB',
    padding: '30px',
    borderRadius: '5px',
    border: '1px solid #C1A68D',
    marginBottom: '20px',
    minHeight: '200px',
    boxShadow: '2px 2px 10px rgba(0,0,0,0.05)',
  },
  letterContent: {
    fontSize: '20px',
    color: '#4A3B32',
    lineHeight: '1.6',
    whiteSpace: 'pre-wrap',
    fontStyle: 'italic',
  },
  timer: {
    fontSize: '36px',
    color: '#8C271E',
    textAlign: 'center',
    fontWeight: 'bold',
    margin: '0',
  },
  waxSeal: {
    width: '100px',
    height: '100px',
    backgroundColor: '#8C271E',
    borderRadius: '50%',
    margin: '0 auto 30px auto',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: '3px solid #60150e',
    boxShadow: 'inset 0 0 10px rgba(0,0,0,0.5), 0 4px 6px rgba(0,0,0,0.3)',
  },
  waxText: {
    color: '#F4ECD8',
    fontWeight: 'bold',
    letterSpacing: '2px',
  },
  vintageText: {
    fontSize: '18px',
    color: '#4A3B32',
    textAlign: 'center',
    marginBottom: '20px',
  }
};